### ISSUE TITLE
process crashed when zed camera is pulled off while recording svo file.

### ISSUE THREAD

**Issue by PenguiNess** [stereolabs/zed-examples#537]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

I have came up with an issue recently while i was developing my program on nvidia agx box with zed-sdk, using svo recording functions like enableRecording and disableRecording. At first，everything went on fine if i plugged  in zed usb camera, but while i pulled off zed camera, i found no camera on in my program, then i tried to close it, then my process crash, crash trace like: 
#0  0x0000007fb4b04c88 in sl::Camera::disableRecording() () at /usr/local/zed/lib/libsl_zed.so
#1  0x0000007fb4b087b0 in sl::Camera::close() () at /usr/local/zed/lib/libsl_zed.so, 
i have thread to detect zed camera, if finding zed camera is off, i will try to close it. but why would it crash when svo recording is going on? Am I do something inproper?  

### Steps to Reproduce

1.
  zed.enableRecording(RecordingParameters(path_output, SVO_COMPRESSION_MODE::H264));
  InitParameters init_parameters;
  init_parameters.camera_resolution = RESOLUTION::HD1080; // Use HD1080 video mode
  init_parameters.depth_mode = DEPTH_MODE::ULTRA; // Use ULTRA depth mode
  zed.open(init_parameters);
2.
   Pull off zed camera usb wire, and Close zed instance.
3. 
  process crash at zed::Camera::close when calling disableRecording internally.

### Expected Result

When zed usb is offline, i wanna close camera manually, but not hoping it to crash when svo recording.

### Actual Result

process crash.

### ZED Camera model

ZED2i

### Environment

```shell
OS: ubuntu18.04. aarch64 
GPU: NVIDIA Jetson AGX Xavier
CUDA: 10.2.89
cuDNN: 8.0.0.180
TensorRT: 7.1.3.0
OpenCV: 4.1.1 compiled CUDA: YES
ZED version: ZED_SDK_Tegra_L4T32.7_v3.8.2.zstd
```

**Comment by PenguiNess** [comment]
Do anybody come up with same issue like me? i would really appreciate it if any one can help on it.
